[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "meiosim"
dynamic = ["version"]
readme = "README.md" 
requires-python = ">=3.10"
dependencies = [
    "numpy",
    "pandas",
    "h5py",
    "scikit-learn",
    "matplotlib",
    "seaborn",
]

authors = [
  {name = "Alexandre Marchal"},
  {name = "Daniele Raimondi"},
]
license = "GPL-3.0-or-later"
description = "A toolbox to simulate crosses and play with quantitative genetics in Python."
[project.urls]
Homepage = "https://github.com/ai-for-genome-interpretation-lab/meiosim"

[tool.setuptools.dynamic]
version = {attr = "meiosim._version.__version__"}

[tool.setuptools.packages.find]
where = ["."]
include = ["meiosim*"]

[tool.setuptools.package-data]
meiosim = ["data/*"]
